// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	repository "flhansen/fitter-login-service/src/repository"

	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: account
func (_m *AccountRepository) CreateAccount(account repository.Account) (int, error) {
	ret := _m.Called(account)

	var r0 int
	if rf, ok := ret.Get(0).(func(repository.Account) int); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(repository.Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAccountById provides a mock function with given fields: id
func (_m *AccountRepository) DeleteAccountById(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccounts provides a mock function with given fields:
func (_m *AccountRepository) DeleteAccounts() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountById provides a mock function with given fields: id
func (_m *AccountRepository) GetAccountById(id int) (repository.Account, error) {
	ret := _m.Called(id)

	var r0 repository.Account
	if rf, ok := ret.Get(0).(func(int) repository.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(repository.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByUsername provides a mock function with given fields: username
func (_m *AccountRepository) GetAccountByUsername(username string) (repository.Account, error) {
	ret := _m.Called(username)

	var r0 repository.Account
	if rf, ok := ret.Get(0).(func(string) repository.Account); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(repository.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountRepository(t mockConstructorTestingTNewAccountRepository) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
