// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HashEngine is an autogenerated mock type for the HashEngine type
type HashEngine struct {
	mock.Mock
}

// HashPassword provides a mock function with given fields: password
func (_m *HashEngine) HashPassword(password []byte) ([]byte, error) {
	ret := _m.Called(password)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHashEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewHashEngine creates a new instance of HashEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHashEngine(t mockConstructorTestingTNewHashEngine) *HashEngine {
	mock := &HashEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
